### PR TITLE
updates to package.json and unittests

### LINKED ISSUE #18: icedfrisby@0.3.0 license should be a valid SPDX license expression
Running npm warns the user "icedfrisby@0.3.0 license should be a valid SPDX license expression".

### PR DESCRIPTION
**Pull request by cvega**
Fixes #18 

I wasn't a 100% certain what BSD clause license you wanted to use so I opted for the basic 3 clause license which I believe is the most popular/standard. It's too bad package.json doesn't support dual licensing because I also noticed the MIT licensing too.

### CODE REVIEW

**Comment by MarkHerhold** [comment]
`intercept-stdout` ... brilliant!

**Comment by MarkHerhold** [comment]
@cvega You should have an email requesting for collaborator access 👍 
I'll get you npm access too soon

**Comment by MarkHerhold** [comment]
@RobertHerhold Could you add @cvega to give him npm publish access? Ty

**Comment by MarkHerhold** [comment]
@cvega I added you as a collaborator to npm. :+1:

**Comment by cvega** [comment]
Awesome, thank you. Having a lot of fun updating the project. As it stands all the libs are up to date, i made the project more mocha friendly, and I added a couple of nice to haves.

The next things I want to do is get the docs auto generated, check out some of the jasmine stuff to see what we can rip out, add a couple of features, etc...

I added a project board. I'm also looking at Frisby 2 to see what if anything we can bring in. Let me know if you have or need anything.

**Comment by cvega** [comment]
Also I don't want to become a bug or get overzealous. I wanted to get the package badge updated. I'm happy to foot some of the bill for the gemnasium service so just let me know.

**Comment by MarkHerhold** [comment]
@cvega I'm thrilled that you are giving this project the attention is needs! I've been unable to do so and am really glad that someone is able to use it and be successful with it. I would not have given you access if I didn't really like the work you were doing and the direction you are taking IcedFrisby. Great job. :+1: 

I'll be sure to leave a note if I think of anything to add to the project board, for sure. :) As for the gemnasium service, I believe it's free because this is a public project (I haven't been paying!) but if we need any new features or service changes, drop me a note and I will be more than happy to spend a few bucks a month to make things happen. Cheers!

**Pull request merged**
