### PR TITLE
Async hooks for before(), after(), finally()

### PR DESCRIPTION
**Pull request by KiNgMaR**
Hi there,

in reference to issue #57, here's a PR showing that async hooks are possible.

Let me know what you think, e.g. if it's better to explicitly check for timeouts within frisby etc.

### CODE REVIEW

**Comment by MarkHerhold** [comment]
This PR looks good to me, but let me review it in full this weekend. @paulmelnikow I'd like to know your thoughts on this as well.

**Comment by MarkHerhold** [comment]
@KiNgMaR Could you please add some docs for this? Perhaps just the fact that you can chain multiple `finally()` blocks would get the point across, but I'd like to document the primary use-case you are implementing for. Thanks!

Great code BTW

**Comment by MarkHerhold** [comment]
Thank you @KiNgMaR !
Released and published as [1.3.0](https://github.com/MarkHerhold/IcedFrisby/commit/2bacda5ee1a9f8a59add4d094d9f111990b4242b)

**Comment by paulmelnikow** [comment]
I'm late to the party, but just wanted to say that this is awesome, @KiNgMaR! 💯

**Pull request merged**
