### PR TITLE
fix(package): update joi to version 13.0.0

### PR DESCRIPTION
**Pull request by paulmelnikow**
Closes #79

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hmm, this version of Joi requires Node 8.3+.

Are we ready to go there @MarkHerhold?

**Comment by MarkHerhold** [comment]
Sorry, but doesn't it seem a little early to force support to Node.js v8? Version 8 isn't even LTS status yet. https://github.com/nodejs/Release

**Comment by paulmelnikow** [comment]
Yea, the more I think about it, the more I agree, and am surprised Joi has jumped ship already.

In terms of a policy, how about supporting the even node versions through the end of the active LTS period, and the odd versions while they're current?

**Comment by MarkHerhold** [comment]
My only guess is that Joi will continue to maintain their older versions or that they are pushing forwards to help reduce maintainer costs.

Going forward, I'm fine with supporting active LTS and newer. 👍

**Pull request closed without merging**
