### PR TITLE
futureproof icedfrisby

### PR DESCRIPTION
**Pull request by cvega**
Upgraded all of the dependencies on the project to latest stable with the exception of lodash. Lodash was upgraded to the latest stable 3.x branch (4.x being the latest). All 245 tests passed.

### CODE REVIEW

**Comment by cvega** [comment]
I use this library and like it a lot. I'd love to see pull request get accepted or get some feedback. I was having a big issue with the bug mentioned. This seems to fix it.

I notice the you haven't updated in awhile. If you're looking for a maintainer let me know.

**Comment by RobertHerhold** [comment]
Ping @MarkHerhold

**Comment by MarkHerhold** [comment]
Hi @cvega , thanks for the PR!

I haven't had much time to dedicate to IcedFrisby. Would you consider becoming a maintainer of this project?

I see that this would also depricate support for Node.js <= 0.12, which is fine by me since support for Node.js 0.12 will be over by the end of this year. Could you include a note in the README about IcedFrisby only supporting Node.js 4+?

**Comment by cvega** [comment]
I will add the note this evening once I get home. I would definitely consider becoming a maintainer. We're building some tooling around icedfrisby so it's important to me that it continues to be a useful tool.

I'm also playing around with some of the tests to validate console output and intercepting stdout. (TODO's exist in the test files for these).

**Comment by cvega** [comment]
Just a heads up, I bumped the version for the change log.

**Comment by MarkHerhold** [comment]
:+1:

**Pull request merged**
